# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src
src/civetweb/include
src/reflect
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_MulleCivetWeb-import-private.h
src/reflect/_MulleCivetWeb-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/import-private.h
)

#
# contents selected with patternfile ??-header--private-headers
#
set( PRIVATE_HEADERS
src/MulleCivetWebRequest+Private.h
src/MulleCivetWebResponse+Private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_MulleCivetWeb-export.h
src/reflect/_MulleCivetWeb-import.h
src/reflect/_MulleCivetWeb-include.h
src/reflect/_MulleCivetWeb-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/import.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/MulleCivetWebRequest+NSURL.h
src/MulleCivetWebRequest.h
src/MulleCivetWebResponse.h
src/MulleCivetWebServer.h
src/MulleCivetWebTextResponse.h
src/MulleCivetWeb.h
src/MulleObjCLoader+MulleCivetWeb.h
src/NSURL+MulleCivetWeb.h
src/NSURL+NSDictionary.h
src/civetweb/include/civetweb.h
)

