#
# This file will be included by cmake/share/sources.cmake
#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`.
# Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleCivetWebRequest+NSURL.m
src/MulleCivetWebRequest.m
src/MulleCivetWebResponse.m
src/MulleCivetWebServer.m
src/MulleCivetWebTextResponse.m
src/MulleCivetWeb.m
src/NSURL+MulleCivetWeb.m
src/NSURL+NSDictionary.m
src/civetweb/src/civetweb.c
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleCivetWeb.m
)
