/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_civet_web_versioncheck_h__
#define mulle_civet_web_versioncheck_h__

#if defined( MULLE_FOUNDATION_VERSION)
# ifndef MULLE_FOUNDATION_VERSION_MIN
#  define MULLE_FOUNDATION_VERSION_MIN  ((0UL << 20) | (22 << 8) | 1)
# endif
# ifndef MULLE_FOUNDATION_VERSION_MAX
#  define MULLE_FOUNDATION_VERSION_MAX  ((0UL << 20) | (23 << 8) | 0)
# endif
# if MULLE_FOUNDATION_VERSION < MULLE_FOUNDATION_VERSION_MIN
#  error "MulleFoundation is too old"
# endif
# if MULLE_FOUNDATION_VERSION >= MULLE_FOUNDATION_VERSION_MAX
#  error "MulleFoundation is too new"
# endif
#endif

#if defined( MULLE_OBJC_HTTP_FOUNDATION_VERSION)
# ifndef MULLE_OBJC_HTTP_FOUNDATION_VERSION_MIN
#  define MULLE_OBJC_HTTP_FOUNDATION_VERSION_MIN  ((0UL << 20) | (18 << 8) | 6)
# endif
# ifndef MULLE_OBJC_HTTP_FOUNDATION_VERSION_MAX
#  define MULLE_OBJC_HTTP_FOUNDATION_VERSION_MAX  ((0UL << 20) | (19 << 8) | 0)
# endif
# if MULLE_OBJC_HTTP_FOUNDATION_VERSION < MULLE_OBJC_HTTP_FOUNDATION_VERSION_MIN
#  error "MulleObjCHTTPFoundation is too old"
# endif
# if MULLE_OBJC_HTTP_FOUNDATION_VERSION >= MULLE_OBJC_HTTP_FOUNDATION_VERSION_MAX
#  error "MulleObjCHTTPFoundation is too new"
# endif
#endif

#endif
