      { @selector( MulleObjCLoader), @selector( MulleFoundation) },      // 47a9beb6;MulleObjCLoader;46ed3b36;MulleFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCArchiverFoundation) },      // 47a9beb6;MulleObjCLoader;98076059;MulleObjCArchiverFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCCalendarFoundation) },      // 47a9beb6;MulleObjCLoader;6b608d36;MulleObjCCalendarFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCDecimalFoundation) },      // 47a9beb6;MulleObjCLoader;f04a7a28;MulleObjCDecimalFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCHTTPFoundation) },      // 47a9beb6;MulleObjCLoader;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCKVCFoundation) },      // 47a9beb6;MulleObjCLoader;4f2544f7;MulleObjCKVCFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCLockFoundation) },      // 47a9beb6;MulleObjCLoader;86a97828;MulleObjCLockFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCMathFoundation) },      // 47a9beb6;MulleObjCLoader;37da74b9;MulleObjCMathFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCOSFoundation) },      // 47a9beb6;MulleObjCLoader;94ffe970;MulleObjCOSFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCPlistFoundation) },      // 47a9beb6;MulleObjCLoader;e8aa8d92;MulleObjCPlistFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCUnicodeFoundation) },      // 47a9beb6;MulleObjCLoader;ab2bbded;MulleObjCUnicodeFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( MulleCivetWebRequest), @selector( NSURL) },      // 40de10e7;MulleCivetWebRequest;6b1e8f73;NSURL
      { @selector( MulleCivetWebRequest), @selector( Private) },      // 40de10e7;MulleCivetWebRequest;01f2cacd;Private
      { @selector( MulleCivetWebRequest), MULLE_OBJC_NO_CATEGORYID },      // 40de10e7;MulleCivetWebRequest;;
      { @selector( MulleCivetWebResponse), MULLE_OBJC_NO_CATEGORYID },      // f07fcd21;MulleCivetWebResponse;;
      { @selector( MulleCivetWebServer), MULLE_OBJC_NO_CATEGORYID },      // 7d0338e7;MulleCivetWebServer;;
      { @selector( MulleCivetWebTextResponse), MULLE_OBJC_NO_CATEGORYID },      // 717eadd0;MulleCivetWebTextResponse;;
      { @selector( NSDictionary), @selector( NSDictionaryPercentEncodedPrinter) },      // 8b2abcad;NSDictionary;166fe095;NSDictionaryPercentEncodedPrinter
      { @selector( NSString), @selector( NSDictionaryPercentEncodedParser) },      // 1994a171;NSString;df739382;NSDictionaryPercentEncodedParser
      { @selector( NSURL), @selector( MulleCivetWeb) },      // 6b1e8f73;NSURL;ba3d249e;MulleCivetWeb
      { @selector( NSURL), @selector( NSDictionary) },      // 6b1e8f73;NSURL;8b2abcad;NSDictionary
