/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_civet_web_import_h__
#define _mulle_civet_web_import_h__

// How to tweak the following MulleFoundation #import
//    remove:          `mulle-sourcetree mark MulleFoundation no-header`
//    rename:          `mulle-sourcetree mark MulleFoundation set include whatever.h`
//    toggle public:   `mulle-sourcetree mark MulleFoundation [no-]public`
//    toggle optional: `mulle-sourcetree mark MulleFoundation [no-]require`
//    remove for os:   `mulle-sourcetree mark MulleFoundation no-os-<osname>`
# import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

#include "_MulleCivetWeb-include.h"


#endif
