      { @selector( MulleObjCLoader), @selector( MulleObjCHTTPFoundation) },      // 47a9beb6;MulleObjCLoader;457d3115;MulleObjCHTTPFoundation
      { @selector( MulleCivetWebRequest), @selector( NSURL) },      // 40de10e7;MulleCivetWebRequest;6b1e8f73;NSURL
      { @selector( MulleCivetWebRequest), @selector( Private) },      // 40de10e7;MulleCivetWebRequest;01f2cacd;Private
      { @selector( MulleCivetWebRequest), MULLE_OBJC_NO_CATEGORYID },      // 40de10e7;MulleCivetWebRequest;;
      { @selector( MulleCivetWebResponse), MULLE_OBJC_NO_CATEGORYID },      // f07fcd21;MulleCivetWebResponse;;
      { @selector( MulleCivetWebServer), MULLE_OBJC_NO_CATEGORYID },      // 7d0338e7;MulleCivetWebServer;;
      { @selector( MulleCivetWebTextResponse), MULLE_OBJC_NO_CATEGORYID },      // 717eadd0;MulleCivetWebTextResponse;;
      { @selector( NSDictionary), @selector( NSDictionaryPercentEncodedPrinter) },      // 8b2abcad;NSDictionary;166fe095;NSDictionaryPercentEncodedPrinter
      { @selector( NSString), @selector( NSDictionaryPercentEncodedParser) },      // 1994a171;NSString;df739382;NSDictionaryPercentEncodedParser
      { @selector( NSURL), @selector( MulleCivetWeb) },      // 6b1e8f73;NSURL;ba3d249e;MulleCivetWeb
      { @selector( NSURL), @selector( NSDictionary) },      // 6b1e8f73;NSURL;8b2abcad;NSDictionary
