#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleCivetWebRequest.m
src/MulleCivetWebResponse.m
src/MulleCivetWebServer.m
src/MulleCivetWeb.m
src/civetweb/src/civetweb.c
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleCivetWeb.m
)
